#!/bin/sh
CURRENT_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/brightness)
MAXIMAL_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/max_brightness)
MINIMAL_BRIGHTNESS=0
STEP_BRIGHTNESS=1000
MULTIPLIER="$1"
DELTA_BRIGHTNESS=$((MULTIPLIER * STEP_BRIGHTNESS))
DESIRED_NEW_BRIGHTNESS=$((CURRENT_BRIGHTNESS + DELTA_BRIGHTNESS))
CLAMPED_NEW_BRIGHTNESS=$((DESIRED_NEW_BRIGHTNESS < MINIMAL_BRIGHTNESS ? MINIMAL_BRIGHTNESS : DESIRED_NEW_BRIGHTNESS > MAXIMAL_BRIGHTNESS ? MAXIMAL_BRIGHTNESS : DESIRED_NEW_BRIGHTNESS))
echo "${CLAMPED_NEW_BRIGHTNESS}" > /sys/class/backlight/intel_backlight/brightness
