#!/bin/sh
STEP_VOLUME=1
MULTIPLIER="$1"
MULTIPLIER_WITHOUT_SIGN="${MULTIPLIER:1}"
MULTIPLIER_SIGN="${MULTIPLIER:0:1}"
ABSOLUTE_DELTA_VOLUME=$((MULTIPLIER_WITHOUT_SIGN * STEP_VOLUME))
wpctl set-volume @DEFAULT_AUDIO_SINK@ "${ABSOLUTE_DELTA_VOLUME}%${MULTIPLIER_SIGN}"
